spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 746656202102-5p44klkpb5nqh5sa51e7hsviiah8352s.apps.googleusercontent.com
            client-secret: YOUR_ACTUAL_CLIENT_SECRET

  # H2 Database Configuration
  datasource:
    url: jdbc:h2:mem:movie_db;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:

  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  # H2 Console Configuration
  h2:
    console:
      enabled: true
      path: /h2-console

# Server port (if needed)
server:
  port: 8080
